### ISSUE TITLE
add vpavlin's bash aliases docker

### ISSUE THREAD

**Issue by goern** [LalatenduMohanty/centos7-container-app-vagrant-box#44] opened 2015-07-17 12:25 UTC
Integrate https://raw.githubusercontent.com/vpavlin/docker-tools/master/bash_aliases_docker so that the user has some convenient docker aliases at hand...

**Comment by vpavlin** [comment] 2015-07-17 12:26
Duplicate of #15

**Closed as completed** 2015-07-17 12:28 UTC
