### ISSUE TITLE
Rebuild vagrant box with latest bits from CentOS7 (as a newer version on k8s available)

### ISSUE THREAD

**Issue by langdon** [LalatenduMohanty/centos7-container-app-vagrant-box#29] opened 2015-05-14 20:27 UTC
In the latest version, kube seems to have some weird issues going on. However, they are solved by a yum update. May be a respin would be a good idea.

**Comment by LalatenduMohanty** [comment] 2015-05-15 09:03
@whitel sure, I would do a respin.

**Comment by LalatenduMohanty** [comment] 2015-05-18 13:57
@whitel do you mean there is some issue with  kubernetes-0.15.0-0.3.git0ea87e4.el7.x86_64?

As I am seeing one (as below)

```
[vagrant@localhost ~]$ systemctl status kube-apiserver
kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; enabled)
   Active: failed (Result: start-limit) since Mon 2015-05-18 09:42:19 EDT; 11min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 694 ExecStart=/usr/bin/kube-apiserver $KUBE_LOGTOSTDERR $KUBE_LOG_LEVEL $KUBE_ETCD_SERVERS $KUBE_API_ADDRESS $KUBE_API_PORT $KUBELET_PORT $KUBE_ALLOW_PRIV $KUBE_SERVICE_ADDRESSES $KUBE_ADMISSION_CONTROL $KUBE_API_ARGS (code=exited, status=255)
 Main PID: 694 (code=exited, status=255)
   CGroup: /system.slice/kube-apiserver.service
```

**Comment by langdon** [comment] 2015-05-18 14:05
I am not sure as I have yum updated already. Basically, with 1.1 many of us were getting weird issues in kube. For me, kubectl get endpoints was returning weird results. All issues went away after a yum update. Not sure if the problem was mismatched kube versions or if it was an issue with a particular rev.

**Comment by LalatenduMohanty** [comment] 2015-05-20 10:27
@whitel so a simple reboot of the vagrant box after `vagrant up` fixes the issue. But I am getting the issue everytime I do a `vagrant up`. Any suggestion?

**Comment by LalatenduMohanty** [comment] 2015-05-20 10:43
cc @kbsingh

**Comment by langdon** [comment] 2015-05-20 14:44
@LalatenduMohanty maybe try restarting all the kube services/etcd/docker in the provision step?

**Comment by langdon** [comment] 2015-05-20 14:56
@kbsingh @lalatendumohanty another thought, can we introduce a reboot in to the build process? And see if that helps?

**Comment by LalatenduMohanty** [comment] 2015-05-20 14:58
@whitel yeah, I am also in favour of putting the reboot after the build process. may be in the %post section. @kbsingh thoughts?

**Comment by LalatenduMohanty** [comment] 2015-05-20 15:01
@whitel btw if you do "vagrant init atomicapp/dev-testing; vagrant up; vagrant ssh ; kubectl get minions" you should be to see the issue.

**Comment by LalatenduMohanty** [comment] 2015-05-21 13:01
@whitel @kbsingh putting reboot on %post does not help. Did a scratch build and tested

**Comment by jasonbrooks** [comment] 2015-05-22 16:12
@LalatenduMohanty  I can reproduce w/ atomicapp/dev-testing, but with the the atomicapp/dev box, which is what the project's README talks about, I'm not getting any apiserver issues...

**Comment by LalatenduMohanty** [comment] 2015-05-25 07:45
@jasonbrooks thats correct. You should see the issue with atomicapp/dev-testing. Thanks for confirming

**Comment by LalatenduMohanty** [comment] 2015-06-04 13:35
So the issue is "kube-apiserver" does not go to running state when we start the VM (e.g. vagarant up).

We are enabling the kube services while building the images hence expecting them to run while starting the image.

This issue came after we rebuild the image using kubernetes-0.15.0-0.3.git0ea87e4.el7.x86_64. We had not seen this previous k8ns.
To reproduce the issue :
- vagrant init atomicapp/dev-testing
- vagrant up
- vagrant ssh

**Comment by LalatenduMohanty** [comment] 2015-06-04 13:56
[vagrant@localhost ~]$ sudo journalctl -u kube-apiserver --full --no-pager

-- Logs begin at Thu 2015-06-04 09:42:12 EDT, end at Thu 2015-06-04 09:49:44 EDT. --
Jun 04 09:42:27 localhost.localdomain systemd[1]: Starting Kubernetes API Server...
Jun 04 09:42:27 localhost.localdomain systemd[1]: Started Kubernetes API Server.
Jun 04 09:42:28 localhost.localdomain kube-apiserver[546]: I0604 09:42:28.220489     546 plugins.go:70] No cloud provider specified.
Jun 04 09:42:28 localhost.localdomain kube-apiserver[546]: F0604 09:42:28.225043     546 master.go:220] Unable to find suitable network address.error='Unable to select an IP.' . Will try again in 5 seconds. Set the public address directly to avoid this wait.
Jun 04 09:42:28 localhost.localdomain systemd[1]: kube-apiserver.service: main process exited, code=exited, status=255/n/a
Jun 04 09:42:28 localhost.localdomain systemd[1]: Unit kube-apiserver.service entered failed state.
Jun 04 09:42:28 localhost.localdomain systemd[1]: kube-apiserver.service holdoff time over, scheduling restart.
Jun 04 09:42:28 localhost.localdomain systemd[1]: Stopping Kubernetes API Server...
Jun 04 09:42:28 localhost.localdomain systemd[1]: Starting Kubernetes API Server...
Jun 04 09:42:28 localhost.localdomain systemd[1]: Started Kubernetes API Server.
Jun 04 09:42:28 localhost.localdomain kube-apiserver[589]: I0604 09:42:28.478175     589 plugins.go:70] No cloud provider specified.
Jun 04 09:42:28 localhost.localdomain kube-apiserver[589]: F0604 09:42:28.486134     589 master.go:220] Unable to find suitable network address.error='Unable to select an IP.' . Will try again in 5 seconds. Set the public address directly to avoid this wait.
Jun 04 09:42:28 localhost.localdomain systemd[1]: kube-apiserver.service: main process exited, code=exited, status=255/n/a
Jun 04 09:42:28 localhost.localdomain systemd[1]: Unit kube-apiserver.service entered failed state.
Jun 04 09:42:28 localhost.localdomain systemd[1]: kube-apiserver.service holdoff time over, scheduling restart.
Jun 04 09:42:28 localhost.localdomain systemd[1]: Stopping Kubernetes API Server...
Jun 04 09:42:28 localhost.localdomain systemd[1]: Starting Kubernetes API Server...
Jun 04 09:42:28 localhost.localdomain systemd[1]: Started Kubernetes API Server.
Jun 04 09:42:28 localhost.localdomain kube-apiserver[629]: I0604 09:42:28.690726     629 plugins.go:70] No cloud provider specified.
Jun 04 09:42:28 localhost.localdomain kube-apiserver[629]: F0604 09:42:28.703801     629 master.go:220] Unable to find suitable network address.error='Unable to select an IP.' . Will try again in 5 seconds. Set the public address directly to avoid this wait.
Jun 04 09:42:28 localhost.localdomain kube-apiserver[629]: E0604 09:42:28.704662     629 reflector.go:123] Failed to list *api.Namespace: Get http://127.0.0.1:8080/api/v1beta3/namespaces: dial tcp 127.0.0.1:8080: connection refused
Jun 04 09:42:28 localhost.localdomain systemd[1]: kube-apiserver.service: main process exited, code=exited, status=255/n/a
Jun 04 09:42:28 localhost.localdomain systemd[1]: Unit kube-apiserver.service entered failed state.
Jun 04 09:42:28 localhost.localdomain systemd[1]: kube-apiserver.service holdoff time over, scheduling restart.
Jun 04 09:42:28 localhost.localdomain systemd[1]: Stopping Kubernetes API Server...
Jun 04 09:42:28 localhost.localdomain systemd[1]: Starting Kubernetes API Server...
Jun 04 09:42:28 localhost.localdomain systemd[1]: Started Kubernetes API Server.
Jun 04 09:42:28 localhost.localdomain kube-apiserver[663]: I0604 09:42:28.894065     663 plugins.go:70] No cloud provider specified.
Jun 04 09:42:28 localhost.localdomain kube-apiserver[663]: E0604 09:42:28.905271     663 reflector.go:123] Failed to list *api.ResourceQuota: Get http://127.0.0.1:8080/api/v1beta3/resourcequotas: dial tcp 127.0.0.1:8080: connection refused
Jun 04 09:42:28 localhost.localdomain kube-apiserver[663]: E0604 09:42:28.906069     663 reflector.go:123] Failed to list *api.LimitRange: Get http://127.0.0.1:8080/api/v1beta3/limitranges: dial tcp 127.0.0.1:8080: connection refused
Jun 04 09:42:28 localhost.localdomain kube-apiserver[663]: E0604 09:42:28.906121     663 reflector.go:123] Failed to list *api.Namespace: Get http://127.0.0.1:8080/api/v1beta3/namespaces: dial tcp 127.0.0.1:8080: connection refused
Jun 04 09:42:28 localhost.localdomain kube-apiserver[663]: F0604 09:42:28.908200     663 master.go:220] Unable to find suitable network address.error='Unable to select an IP.' . Will try again in 5 seconds. Set the public address directly to avoid this wait.
Jun 04 09:42:28 localhost.localdomain systemd[1]: kube-apiserver.service: main process exited, code=exited, status=255/n/a
Jun 04 09:42:28 localhost.localdomain systemd[1]: Unit kube-apiserver.service entered failed state.
Jun 04 09:42:29 localhost.localdomain systemd[1]: kube-apiserver.service holdoff time over, scheduling restart.
Jun 04 09:42:29 localhost.localdomain systemd[1]: Stopping Kubernetes API Server...
Jun 04 09:42:29 localhost.localdomain systemd[1]: Starting Kubernetes API Server...
Jun 04 09:42:29 localhost.localdomain systemd[1]: Started Kubernetes API Server.
Jun 04 09:42:29 localhost.localdomain kube-apiserver[694]: I0604 09:42:29.105212     694 plugins.go:70] No cloud provider specified.
Jun 04 09:42:29 localhost.localdomain kube-apiserver[694]: E0604 09:42:29.107880     694 reflector.go:123] Failed to list *api.ResourceQuota: Get http://127.0.0.1:8080/api/v1beta3/resourcequotas: dial tcp 127.0.0.1:8080: connection refused
Jun 04 09:42:29 localhost.localdomain kube-apiserver[694]: E0604 09:42:29.107945     694 reflector.go:123] Failed to list *api.LimitRange: Get http://127.0.0.1:8080/api/v1beta3/limitranges: dial tcp 127.0.0.1:8080: connection refused
Jun 04 09:42:29 localhost.localdomain kube-apiserver[694]: E0604 09:42:29.107976     694 reflector.go:123] Failed to list *api.Namespace: Get http://127.0.0.1:8080/api/v1beta3/namespaces: dial tcp 127.0.0.1:8080: connection refused
Jun 04 09:42:29 localhost.localdomain kube-apiserver[694]: F0604 09:42:29.110097     694 master.go:220] Unable to find suitable network address.error='Unable to select an IP.' . Will try again in 5 seconds. Set the public address directly to avoid this wait.
Jun 04 09:42:29 localhost.localdomain systemd[1]: kube-apiserver.service: main process exited, code=exited, status=255/n/a
Jun 04 09:42:29 localhost.localdomain systemd[1]: Unit kube-apiserver.service entered failed state.
Jun 04 09:42:29 localhost.localdomain systemd[1]: kube-apiserver.service holdoff time over, scheduling restart.
Jun 04 09:42:29 localhost.localdomain systemd[1]: Stopping Kubernetes API Server...
Jun 04 09:42:29 localhost.localdomain systemd[1]: Starting Kubernetes API Server...
Jun 04 09:42:29 localhost.localdomain systemd[1]: kube-apiserver.service start request repeated too quickly, refusing to start.
Jun 04 09:42:29 localhost.localdomain systemd[1]: Failed to start Kubernetes API Server.
Jun 04 09:42:29 localhost.localdomain systemd[1]: Unit kube-apiserver.service entered failed state.

**Comment by derekwaynecarr** [comment] 2015-06-16 18:16
The fix is the following:

--address=127.0.0.1: DEPRECATED: see --insecure_bind_address instead

moved to the following:

```
$ vi /etc/kubernetes/apiserver
```

```
# The address on the local server to listen to.
KUBE_API_ADDRESS="--insecure_bind_address=127.0.0.1"
```

```
$ systemctl daemon-reload
$ systemctl restart kube-apiserver
```

Things looked good.

**Comment by LalatenduMohanty** [comment] 2015-06-17 10:47
Koji build i.e. https://cbs.centos.org/koji/taskinfo?taskID=15160 with the fix i.e. https://github.com/LalatenduMohanty/centos7-container-app-vagrant-box/pull/38
@derekwaynecarr Still seeing the issue after replaced --address with --insecure_bind_address. Please note that we are only seeing this issue when we first start the vagrant box i.e. "vagrant up". a reboot  or service restart fixes the issue. See logs below

``` r
vagrant@localhost ~]$ systemctl status kube-apiserver.service 
kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; enabled)
   Active: failed (Result: start-limit) since Wed 2015-06-17 06:19:16 EDT; 1min 59s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 673 ExecStart=/usr/bin/kube-apiserver $KUBE_LOGTOSTDERR $KUBE_LOG_LEVEL $KUBE_ETCD_SERVERS $KUBE_API_ADDRESS $KUBE_API_PORT $KUBELET_PORT $KUBE_ALLOW_PRIV $KUBE_SERVICE_ADDRESSES $KUBE_ADMISSION_CONTROL $KUBE_API_ARGS (code=exited, status=255)
 Main PID: 673 (code=exited, status=255)
   CGroup: /system.slice/kube-apiserver.service
```

Copied the content of the file i.e. /etc/kubernetes/apiserver 

``` r
$ cat /etc/kubernetes/apiserver 
###
# kubernetes system config
#
# The following values are used to configure the kube-apiserver
#

# The insecure_bind_address on the local server to listen to.
KUBE_API_ADDRESS="--insecure_bind_address=127.0.0.1"

# The port on the local server to listen on.
# KUBE_API_PORT="--port=8080"

# Port minions listen on
# KUBELET_PORT="--kubelet_port=10250"

# Comma separated list of nodes in the etcd cluster
KUBE_ETCD_SERVERS="--etcd_servers=http://127.0.0.1:4001"

# Address range to use for services
KUBE_SERVICE_ADDRESSES="--portal_net=10.254.0.0/16"

# default admission control policies
KUBE_ADMISSION_CONTROL="--admission_control=NamespaceAutoProvision,LimitRanger,ResourceQuota"

# Add you own!
KUBE_API_ARGS=""
```

``` r
$ sudo journalctl -u kube-apiserver --full --no-pager
-- Logs begin at Wed 2015-06-17 06:19:13 EDT, end at Wed 2015-06-17 06:21:43 EDT. --
Jun 17 06:19:15 localhost.localdomain systemd[1]: Starting Kubernetes API Server...
Jun 17 06:19:15 localhost.localdomain systemd[1]: Started Kubernetes API Server.
Jun 17 06:19:15 localhost.localdomain kube-apiserver[551]: I0617 06:19:15.627649     551 plugins.go:70] No cloud provider specified.
Jun 17 06:19:15 localhost.localdomain kube-apiserver[551]: E0617 06:19:15.642904     551 reflector.go:123] Failed to list *api.ResourceQuota: Get http://127.0.0.1:8080/api/v1beta3/resourcequotas: dial tcp 127.0.0.1:8080: connection refused
Jun 17 06:19:15 localhost.localdomain kube-apiserver[551]: E0617 06:19:15.643071     551 reflector.go:123] Failed to list *api.LimitRange: Get http://127.0.0.1:8080/api/v1beta3/limitranges: dial tcp 127.0.0.1:8080: connection refused
Jun 17 06:19:15 localhost.localdomain kube-apiserver[551]: E0617 06:19:15.643145     551 reflector.go:123] Failed to list *api.Namespace: Get http://127.0.0.1:8080/api/v1beta3/namespaces: dial tcp 127.0.0.1:8080: connection refused
Jun 17 06:19:15 localhost.localdomain systemd[1]: kube-apiserver.service: main process exited, code=exited, status=255/n/a
Jun 17 06:19:15 localhost.localdomain systemd[1]: Unit kube-apiserver.service entered failed state.
Jun 17 06:19:15 localhost.localdomain kube-apiserver[551]: F0617 06:19:15.649559     551 master.go:220] Unable to find suitable network address.error='Unable to select an IP.' . Will try again in 5 seconds. Set the public address directly to avoid this wait.
Jun 17 06:19:15 localhost.localdomain systemd[1]: kube-apiserver.service holdoff time over, scheduling restart.
Jun 17 06:19:15 localhost.localdomain systemd[1]: Stopping Kubernetes API Server...
Jun 17 06:19:15 localhost.localdomain systemd[1]: Starting Kubernetes API Server...
Jun 17 06:19:15 localhost.localdomain systemd[1]: Started Kubernetes API Server.
Jun 17 06:19:15 localhost.localdomain kube-apiserver[588]: I0617 06:19:15.875470     588 plugins.go:70] No cloud provider specified.
Jun 17 06:19:15 localhost.localdomain kube-apiserver[588]: F0617 06:19:15.885098     588 master.go:220] Unable to find suitable network address.error='Unable to select an IP.' . Will try again in 5 seconds. Set the public address directly to avoid this wait.
Jun 17 06:19:15 localhost.localdomain systemd[1]: kube-apiserver.service: main process exited, code=exited, status=255/n/a
Jun 17 06:19:15 localhost.localdomain systemd[1]: Unit kube-apiserver.service entered failed state.
Jun 17 06:19:15 localhost.localdomain systemd[1]: kube-apiserver.service holdoff time over, scheduling restart.
Jun 17 06:19:15 localhost.localdomain systemd[1]: Stopping Kubernetes API Server...
Jun 17 06:19:15 localhost.localdomain systemd[1]: Starting Kubernetes API Server...
Jun 17 06:19:16 localhost.localdomain systemd[1]: Started Kubernetes API Server.
Jun 17 06:19:16 localhost.localdomain kube-apiserver[624]: I0617 06:19:16.096311     624 plugins.go:70] No cloud provider specified.
Jun 17 06:19:16 localhost.localdomain kube-apiserver[624]: F0617 06:19:16.100042     624 master.go:220] Unable to find suitable network address.error='Unable to select an IP.' . Will try again in 5 seconds. Set the public address directly to avoid this wait.
Jun 17 06:19:16 localhost.localdomain systemd[1]: kube-apiserver.service: main process exited, code=exited, status=255/n/a
Jun 17 06:19:16 localhost.localdomain systemd[1]: Unit kube-apiserver.service entered failed state.
Jun 17 06:19:16 localhost.localdomain systemd[1]: kube-apiserver.service holdoff time over, scheduling restart.
Jun 17 06:19:16 localhost.localdomain systemd[1]: Stopping Kubernetes API Server...
Jun 17 06:19:16 localhost.localdomain systemd[1]: Starting Kubernetes API Server...
Jun 17 06:19:16 localhost.localdomain systemd[1]: Started Kubernetes API Server.
Jun 17 06:19:16 localhost.localdomain kube-apiserver[644]: I0617 06:19:16.302031     644 plugins.go:70] No cloud provider specified.
Jun 17 06:19:16 localhost.localdomain kube-apiserver[644]: F0617 06:19:16.314500     644 master.go:220] Unable to find suitable network address.error='Unable to select an IP.' . Will try again in 5 seconds. Set the public address directly to avoid this wait.
Jun 17 06:19:16 localhost.localdomain systemd[1]: kube-apiserver.service: main process exited, code=exited, status=255/n/a
Jun 17 06:19:16 localhost.localdomain systemd[1]: Unit kube-apiserver.service entered failed state.
Jun 17 06:19:16 localhost.localdomain systemd[1]: kube-apiserver.service holdoff time over, scheduling restart.
Jun 17 06:19:16 localhost.localdomain systemd[1]: Stopping Kubernetes API Server...
Jun 17 06:19:16 localhost.localdomain systemd[1]: Starting Kubernetes API Server...
Jun 17 06:19:16 localhost.localdomain systemd[1]: Started Kubernetes API Server.
Jun 17 06:19:16 localhost.localdomain kube-apiserver[673]: I0617 06:19:16.510090     673 plugins.go:70] No cloud provider specified.
Jun 17 06:19:16 localhost.localdomain kube-apiserver[673]: F0617 06:19:16.519126     673 master.go:220] Unable to find suitable network address.error='Unable to select an IP.' . Will try again in 5 seconds. Set the public address directly to avoid this wait.
Jun 17 06:19:16 localhost.localdomain kube-apiserver[673]: E0617 06:19:16.527255     673 reflector.go:123] Failed to list *api.ResourceQuota: Get http://127.0.0.1:8080/api/v1beta3/resourcequotas: dial tcp 127.0.0.1:8080: connection refused
Jun 17 06:19:16 localhost.localdomain kube-apiserver[673]: E0617 06:19:16.528002     673 reflector.go:123] Failed to list *api.LimitRange: Get http://127.0.0.1:8080/api/v1beta3/limitranges: dial tcp 127.0.0.1:8080: connection refused
Jun 17 06:19:16 localhost.localdomain kube-apiserver[673]: E0617 06:19:16.528103     673 reflector.go:123] Failed to list *api.Namespace: Get http://127.0.0.1:8080/api/v1beta3/namespaces: dial tcp 127.0.0.1:8080: connection refused
Jun 17 06:19:16 localhost.localdomain systemd[1]: kube-apiserver.service: main process exited, code=exited, status=255/n/a
Jun 17 06:19:16 localhost.localdomain systemd[1]: Unit kube-apiserver.service entered failed state.
Jun 17 06:19:16 localhost.localdomain systemd[1]: kube-apiserver.service holdoff time over, scheduling restart.
Jun 17 06:19:16 localhost.localdomain systemd[1]: Stopping Kubernetes API Server...
Jun 17 06:19:16 localhost.localdomain systemd[1]: Starting Kubernetes API Server...
Jun 17 06:19:16 localhost.localdomain systemd[1]: kube-apiserver.service start request repeated too quickly, refusing to start.
Jun 17 06:19:16 localhost.localdomain systemd[1]: Failed to start Kubernetes API Server.
Jun 17 06:19:16 localhost.localdomain systemd[1]: Unit kube-apiserver.service entered failed state.

```

**Comment by LalatenduMohanty** [comment] 2015-06-17 10:47
_However restarting the service works fine._

``` r
[vagrant@localhost ~]$ sudo systemctl restart kube-apiserver.service

[vagrant@localhost ~]$ systemctl status kube-apiserver.service
kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; enabled)
   Active: active (running) since Wed 2015-06-17 06:28:08 EDT; 8s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 13997 (kube-apiserver)
   CGroup: /system.slice/kube-apiserver.service
           └─13997 /usr/bin/kube-apiserver --logtostderr=true --v=0 --etcd_servers=http://127.0.0.1:4001 --insecure_bind_address=127.0.0.1 --allow_privileged=false --portal_net=10.254.0.0...

```

I have copied the system logs after the service started sucessfully.

``` r
[vagrant@localhost ~]$ sudo journalctl -u kube-apiserver --full --no-pager

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Jun 17 06:28:08 localhost.localdomain systemd[1]: Starting Kubernetes API Server...
Jun 17 06:28:08 localhost.localdomain systemd[1]: Started Kubernetes API Server.
Jun 17 06:28:08 localhost.localdomain kube-apiserver[13997]: I0617 06:28:08.570297   13997 plugins.go:70] No cloud provider specified.
Jun 17 06:28:08 localhost.localdomain kube-apiserver[13997]: I0617 06:28:08.573328   13997 master.go:224] Will report 192.168.121.86 as public IP address.
Jun 17 06:28:08 localhost.localdomain kube-apiserver[13997]: E0617 06:28:08.574833   13997 reflector.go:123] Failed to list *api.ResourceQuota: Get http://127.0.0.1:8080/api/v1beta3/resourcequotas: dial tcp 127.0.0.1:8080: connection refused
Jun 17 06:28:08 localhost.localdomain kube-apiserver[13997]: E0617 06:28:08.574999   13997 reflector.go:123] Failed to list *api.LimitRange: Get http://127.0.0.1:8080/api/v1beta3/limitranges: dial tcp 127.0.0.1:8080: connection refused
Jun 17 06:28:08 localhost.localdomain kube-apiserver[13997]: E0617 06:28:08.575076   13997 reflector.go:123] Failed to list *api.Namespace: Get http://127.0.0.1:8080/api/v1beta3/namespaces: dial tcp 127.0.0.1:8080: connection refused
Jun 17 06:28:08 localhost.localdomain kube-apiserver[13997]: [restful] 2015/06/17 06:28:08 log.go:30: [restful/swagger] listing is available at https://192.168.121.86:6443/swaggerapi/
Jun 17 06:28:08 localhost.localdomain kube-apiserver[13997]: [restful] 2015/06/17 06:28:08 log.go:30: [restful/swagger] https://192.168.121.86:6443/swaggerui/ is mapped to folder /swagger-ui/
Jun 17 06:28:08 localhost.localdomain kube-apiserver[13997]: I0617 06:28:08.644202   13997 server.go:329] Serving read-only insecurely on 0.0.0.0:7080
Jun 17 06:28:08 localhost.localdomain kube-apiserver[13997]: I0617 06:28:08.644221   13997 server.go:366] Serving securely on 0.0.0.0:6443
Jun 17 06:28:08 localhost.localdomain kube-apiserver[13997]: I0617 06:28:08.644241   13997 server.go:394] Serving insecurely on 127.0.0.1:8080
Jun 17 06:28:09 localhost.localdomain kube-apiserver[13997]: I0617 06:28:09.003669   13997 publish.go:152] setting endpoints for master service "kubernetes" to &{{ } {kubernetes  default    0001-01-01 00:00:00 +0000 UTC <nil> map[] map[]} [{[{192.168.121.86 <nil>}] [{ 6443 TCP}]}]}
Jun 17 06:28:09 localhost.localdomain kube-apiserver[13997]: I0617 06:28:09.050368   13997 publish.go:152] setting endpoints for master service "kubernetes-ro" to &{{ } {kubernetes-ro  default    0001-01-01 00:00:00 +0000 UTC <nil> map[] map[]} [{[{192.168.121.86 <nil>}] [{ 7080 TCP}]}]}
Jun 17 06:28:09 localhost.localdomain kube-apiserver[13997]: I0617 06:28:09.128446   13997 server.go:376] Using self-signed cert (/var/run/kubernetes/apiserver.crt, /var/run/kubernetes/apiserver.key)
```

**Comment by LalatenduMohanty** [comment] 2015-06-17 10:56
Here are the steps that will reproduce the issue for you.

To reproduce the issue :
- vagrant init atomicapp/dev-testing
- vagrant up
- vagrant ssh

**Comment by LalatenduMohanty** [comment] 2015-06-18 15:44
@derekwaynecarr 
Between the systemd unit files of kubernetes-0.15.0-0.3.git0ea87e4.el7.x86_64 and kubernetes-0.9.0-0.3.git96af0c3.el7.x86_64. 
I am seeing " $KUBE_ADMISSION_CONTROL "  as a new thing in kubernetes-0.15.0-0.3.git0ea87e4.el7.x86_64.  

Can it make the issue to show up?

``` r
[vagrant@localhost ~]$ cat /usr/lib/systemd/system/kube-apiserver.service
[Unit]
Description=Kubernetes API Server
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
EnvironmentFile=-/etc/kubernetes/config
EnvironmentFile=-/etc/kubernetes/apiserver
User=kube
ExecStart=/usr/bin/kube-apiserver \
            $KUBE_LOGTOSTDERR \
            $KUBE_LOG_LEVEL \
            $KUBE_ETCD_SERVERS \
            $KUBE_API_ADDRESS \
            $KUBE_API_PORT \
            $KUBELET_PORT \
            $KUBE_ALLOW_PRIV \
            $KUBE_SERVICE_ADDRESSES \
            $KUBE_ADMISSION_CONTROL \
            $KUBE_API_ARGS
Restart=on-failure
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
```

**Comment by LalatenduMohanty** [comment] 2015-06-18 17:06
Thanks to @derekwaynecarr , we came across https://github.com/openshift/origin/blob/master/rel-eng/openshift-master.service. So trying adding "After=network.target" to the systemd unit file of kube-apiserver

``` r
$ cat /usr/lib/systemd/system/kube-apiserver.service
[Unit]
Description=Kubernetes API Server
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=network.target

Service]
EnvironmentFile=-/etc/kubernetes/config
EnvironmentFile=-/etc/kubernetes/apiserver
User=kube
ExecStart=/usr/bin/kube-apiserver \
            $KUBE_LOGTOSTDERR \
            $KUBE_LOG_LEVEL \
            $KUBE_ETCD_SERVERS \
            $KUBE_API_ADDRESS \
            $KUBE_API_PORT \
            $KUBELET_PORT \
            $KUBE_ALLOW_PRIV \
            $KUBE_SERVICE_ADDRESSES \
            $KUBE_ADMISSION_CONTROL \
            $KUBE_API_ARGS
Restart=on-failure
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
```

**Comment by eparis** [comment] 2015-06-18 17:07
you want After, not requires

**Comment by LalatenduMohanty** [comment] 2015-06-18 17:09
Thanks @eparis . Updated my previous comment

**Comment by LalatenduMohanty** [comment] 2015-06-30 12:44
@eparis @derekwaynecarr yes, it solved the issue. The build is at https://cbs.centos.org/koji/taskinfo?taskID=15580.  

It took some time for to understand that there is an issue in Vagrant which was actually using an old image even if I was adding the newly built image for testing i.e. "vagrant box add atomicapp-scratch centos-7-atomicapp-1-1.x86_64.rhevm.ova --force". So I was just wondering why it is not working for us.

**Comment by LalatenduMohanty** [comment] 2015-06-30 12:55
Closing the issue as the issue is not reproducible now

**Closed as completed by LalatenduMohanty** 2015-06-30 12:55 UTC
Labels: enhancement

**Comment by derekwaynecarr** [comment] 2015-06-30 14:39
Awesome, glad we got it figured out for you.

On Tue, Jun 30, 2015 at 8:55 AM, Lalatendu Mohanty <notifications@github.com

**Comment by LalatenduMohanty** [comment] 2015-07-28 14:50
@derekwaynecarr is there any plan to put the fix upstream?

**Comment by derekwaynecarr** [comment] 2015-07-28 18:23
@LalatenduMohanty - I will submit a PR with the updated unit file this afternoon.  Thanks for the reminder.

**Comment by derekwaynecarr** [comment] 2015-07-28 18:50
See upstream PR:
https://github.com/GoogleCloudPlatform/kubernetes/pull/11939
